### ISSUE TITLE
Canal U

### ISSUE THREAD

**Issue by orion2036** [jamontes/plugin.video.latelelibre_fr#1]
I appreciate the work you have done with several videos add-on for Kodi. I am not a coder. I would be happy to see a video add-on for the website https://www.canal-u.tv/
Thank you.

**Comment by jamontes** [comment]
Hi orion2036,
Thanks a lot for let me know about this channel. I've found it very interesting and didn't hear of it before. On the other hand, i have several projects in the way and no so much spare time to afford them all, but i've taken note of this channel as a nice option for an add-on in the future.
Kind regards,
jamontes.

**Comment by orion2036** [comment]
Hi jamontes,
You can improve this code if you want, it is not working correctly but 
it can be a good start
https://github.com/spmjc/plugin.video.freplay/blob/master/resources/lib/channels/canalu.py
Thank you.
